import React, {useState, useEffect} from 'react';
import {createRoot} from 'react-dom/client';
import original from '../source/chat-screen.txt?raw';
import {extractFormulas} from './source';
import './style.css';
import './readability.css';
import './guided.css';
import {GuidedApp, FormulaContext} from './Guide';

const formulas = extractFormulas(original);
const lessons = [
 ['Preparando EVA','El primer «hola» empieza aquí.','Inicializa la conversación y prepara los datos que EVA necesita para responder.','chat','OnVisible'],
 ['Construyendo el chat','Una conversación toma forma.','Conecta la galería, los mensajes y la entrada de texto para dar vida a la pantalla.','galConversacion','Items'],
 ['Enviar mensajes','De una idea a un mensaje.','Sigue el recorrido de lo que escribes, desde el cuadro de texto hasta la conversación.','btnEnviar','OnSelect'],
 ['Buscar respuestas','¿Cómo elige EVA qué decir?','Desarma la búsqueda por palabras clave, una pequeña decisión a la vez.','tmr_escribiendo','OnTimerEnd'],
 ['EVA está escribiendo…','Una pausa que se puede ver.','Dos temporizadores coordinan la espera y los puntos de la conversación.','tmr_puntitos','OnTimerEnd'],
 ['Opciones rápidas','Una pregunta, a un clic.','Ofrece preguntas listas para usar y descubre cómo se resuelven sus respuestas.','btn_choices','OnSelect']
];
const levels = ['Escribe tú mismo','Copia y analicemos','Código complejo'];
function Badge({level=0}) {return <span className={`badge level-${level}`}><i/>{levels[level]}</span>}
function Code({control,property,level=0}) {
 const selected=React.useContext(FormulaContext);
 const [expanded,setExpanded]=useState(selected===`${control}.${property}`);
 useEffect(()=>{if(selected===`${control}.${property}`)setExpanded(true)},[selected,control,property]);
 const [status,setStatus]=useState('Copiar');
 const code = formulas[`${control}.${property}`];
 useEffect(()=>{if(status==='Copiar')return; const t=setTimeout(()=>setStatus('Copiar'),2500);return()=>clearTimeout(t)},[status]);
 async function copy(){try{await navigator.clipboard.writeText(code);setStatus('¡Copiado!')}catch{setStatus('Selecciona el código')}}
 return <section className="code-card" id={`${control}-${property}`}><div className="code-heading"><div><strong>{control}</strong><span className="property">{property}</span></div><button onClick={()=>setExpanded(!expanded)} aria-expanded={expanded} aria-controls={`${control}-${property}-formula`}>{expanded?'Ocultar':'Ver fórmula'} {expanded?'−':'+'}</button></div>{expanded&&<div id={`${control}-${property}-formula`}>{control==='tmr_escribiendo'&&property==='OnTimerEnd'&&<Note warning title="Fórmula original pendiente de revisión">Revisa la coma entre Set y Collect dentro del If, como se explica en el primer paso de esta lección.</Note>}<pre tabIndex="0" aria-label={`${control}, ${property}`}><code>{code ?? 'No se encontró esta propiedad en el archivo original.'}</code></pre><div className="code-footer"><Badge level={level}/><button onClick={copy} aria-label={`Copiar ${control}.${property}`}><span aria-live="polite">{status}</span></button></div></div>}</section>
}
function Concepts({items}){const [active,setActive]=useState(0);return <div className="concept-explorer"><p className="interaction-hint">Selecciona un concepto para explorarlo.</p><div className="concept-tabs">{items.map(([name],i)=><button key={name} aria-pressed={active===i} onClick={()=>setActive(i)}>{name}</button>)}</div><div className="concept-answer" aria-live="polite"><code>{items[active][0]}</code><p>{items[active][1]}</p></div></div>}
function Flow({items}){const [position,setPosition]=useState(0);return <div className="flow-explorer"><span className="interaction-hint">Recorre la secuencia · {position+1} / {items.length}</span><p aria-live="polite"><span>{String(position+1).padStart(2,'0')}</span>{items[position]}</p><div><button disabled={position===0} aria-label="Acción anterior" onClick={()=>setPosition(position-1)}>←</button><div className="flow-dots">{items.map((item,i)=><button key={item} aria-label={`Acción ${i+1}: ${item}`} aria-pressed={i===position} onClick={()=>setPosition(i)}/>)}</div><button disabled={position===items.length-1} aria-label="Acción siguiente" onClick={()=>setPosition(position+1)}>→</button></div></div>}
function Note({children,title='Antes de continuar',warning=false}){return <aside className={`note ${warning?'warning':''}`}><strong>{title}</strong><div>{children}</div></aside>}
function Section({title,children}){return <section className="section"><h2>{title}</h2>{children}</section>}
function ChatPreview(){return <div className="chat-preview"><div className="chat-head"><span className="avatar">E</span><div><strong>EVA Assistant</strong><small>Así comienza la conversación</small></div></div><div className="chat-body"><span className="speaker">EVA</span><div className="bubble">¡Hola! Soy EVA. ¿En qué te puedo ayudar?</div><div className="bubble user">¿Qué es TOEIC?</div><span className="speaker right">Tú</span></div><div className="chat-caption">Vista ilustrativa · los datos viven en Power Apps</div></div>}
const quickQuestions = [...formulas['chat.OnVisible'].matchAll(/\{Texto: "([^"]+)"\}/g)].map(m=>m[1]);
function Content({index}) {
 if(index===0)return <><div className="intro-grid"><div><h2>Prepara el punto de partida</h2><p>Selecciona la pantalla <code>chat</code> y abre su propiedad <code>OnVisible</code>. Esta fórmula se ejecuta cuando llegas a la pantalla.</p><Flow items={['Crear el saludo inicial','Cargar las cuatro preguntas rápidas','Mostrar las opciones y cargar las respuestas']}/></div><ChatPreview/></div><Section title="Tres colecciones, una conversación"><Concepts items={[["colConversacion","Guarda los mensajes y quién los envía. Comienza con el saludo de EVA."],["colOpcionesRapidas","Guarda las cuatro preguntas que se ofrecen al iniciar."],["colRespuestasBot","Copia Title, PalabrasClave, Respuesta y Orden desde respuestasBot."]]}/></Section><Note title="Prepara tus datos en Power Apps"><p>Conecta el origen <code>respuestasBot</code> con las columnas <code>Title</code>, <code>PalabrasClave</code>, <code>Respuesta</code> y <code>Orden</code>. El archivo no incluye sus registros. La guía funciona sin conexión a ese origen; tu chatbot sí lo necesita.</p></Note><Section title="Al abrir la pantalla"><Code control="chat" property="OnVisible" level={1}/><Concepts items={[["ClearCollect()","Vacía una colección y la llena con los registros indicados."],["ShowColumns()","Conserva solo las columnas que necesitamos."],["varMostrarOpciones","Con true, las preguntas rápidas quedan visibles."]]}/></Section><Note title="Pruébalo en clase"><p>Abre otra pantalla y vuelve a chat. ¿Por qué vuelve a aparecer el saludo? ClearCollect reinicia la conversación cada vez que se ejecuta OnVisible.</p></Note><p className="muted">En este archivo, las búsquedas consultan respuestasBot directamente; no usan la copia colRespuestasBot.</p></>;
 if(index===1)return <><div className="intro-grid"><div><h2>Cada control tiene un trabajo</h2><p><code>galConversacion</code> repite una fila por mensaje. Dentro, <code>lbl_message</code> decide qué texto mostrar y cómo presentarlo.</p><p><code>txtMensaje</code> recibe lo que escribes y <code>btnEnviar</code> inicia el envío.</p></div><ChatPreview/></div><Section title="La galería: los mensajes y su espacio"><p>Items conecta los datos. Default señala el registro guardado en varLast. Height reserva espacio para opciones o para el indicador de escritura.</p>{['Items','Default','Height'].map(p=><Code key={p} control="galConversacion" property={p}/>)}</Section><Section title="Un mensaje, dos apariencias"><p>El usuario tiene texto blanco, fondo verde y su burbuja a la derecha. EVA tiene texto negro, fondo gris y su burbuja a la izquierda. <code>ThisItem</code> es el registro de la fila actual.</p>{['Text','Color','Fill','X'].map(p=><Code key={p} control="lbl_message" property={p}/>)}</Section><Section title="La entrada y el botón"><Code control="txtMensaje" property="Default"/><Code control="txtMensaje" property="HintText"/><Code control="btnEnviar" property="Text"/><p>Estos textos en inglés pertenecen al archivo original. En la siguiente lección veremos la acción del botón.</p></Section><Note title="Comprueba que lo entiendes"><p>En X, ¿por qué restamos Self.Width al ancho de Parent? Así la burbuja del usuario cabe dentro de la galería, con 20 de margen.</p></Note></>;
 if(index===2)return <><Section title="El recorrido de tu mensaje"><Flow items={['Leer txtMensaje.Text y guardar varUltimoMensaje','Agregar el mensaje a colConversacion','Guardar el último registro en varLast','Iniciar varPuntitos y ocultar las opciones','Activar varStatus y varEscribiendo','Vaciar txtMensaje con Reset']}/></Section><Section title="La acción del botón"><Code control="btnEnviar" property="OnSelect" level={1}/><p>El botón agrega tu mensaje y activa la espera. La búsqueda de la respuesta está en <code>tmr_escribiendo.OnTimerEnd</code>.</p></Section><Concepts items={[["Set()","Guarda un valor en una variable global."],["Collect()","Agrega un registro sin borrar los anteriores."],["GUID()","Crea un identificador único para el mensaje."],["Last()","Obtiene el último registro de la colección."],["Reset()","Devuelve el cuadro de texto a su valor Default, aquí vacío."]]}/><Note title="Observa antes de copiar"><p>¿Por qué guardamos el texto antes de Reset? Porque el cuadro se vacía; varUltimoMensaje conserva la pregunta para el temporizador.</p></Note><Note title="Detalle del código original"><p>El envío no comprueba si el mensaje está vacío ni bloquea envíos consecutivos durante la espera. Para seguir el ejercicio, envía una pregunta y espera su respuesta.</p></Note></>;
 if(index===3)return <><Note warning title="Revisar en Power Apps antes de la clase"><p>La fórmula original contiene una coma entre <code>Set(varRespuesta, …)</code> y el <code>Collect</code> de la respuesta encontrada. En <code>If</code>, esa coma separa argumentos; no encadena acciones. Esa rama necesita revisión en Power Apps. Conservamos el original sin corregirlo silenciosamente.</p><a href="https://learn.microsoft.com/en-us/power-platform/power-fx/reference/function-if" target="_blank" rel="noreferrer">Consultar la sintaxis de If en Microsoft Learn ↗</a></Note><Section title="La intención de la búsqueda, paso a paso"><Flow items={['Recibir varUltimoMensaje','Normalizar el texto','Separar las palabras clave','Buscar coincidencias','Asignar Puntaje a cada respuesta','Ordenar de mayor a menor','Elegir la primera respuesta','Agregar la respuesta al chat']}/></Section><Section title="01 / Preparar y comparar"><Concepts items={[["With()","Da un nombre local, _msg, al texto preparado para esta búsqueda."],["Lower() + Substitute()","Pasa el mensaje a minúsculas y reemplaza á, é, í, ó, ú por vocales sin tilde."],["Split() + Trim()","Separa PalabrasClave por comas y elimina espacios de los extremos."],["Filter()","Conserva las palabras clave contenidas en el mensaje."]]}/><p>La comparación busca fragmentos dentro del texto, no interpreta su significado. Las palabras clave se pasan a minúsculas, pero sus tildes no se eliminan: prepara el origen de datos con ese detalle en mente.</p></Section><Section title="02 / Dar un puntaje y elegir"><Concepts items={[["CountRows()","Cuenta cuántas palabras clave de una respuesta coinciden."],["AddColumns()","Añade la columna Puntaje a cada registro de respuestasBot."],["colPuntajes","Contiene las respuestas candidatas y su cantidad de coincidencias."],["SortByColumns() + First()","Ordena Puntaje de mayor a menor y toma el primer registro con puntaje positivo."]]}/><p>Si dos respuestas tienen el mismo Puntaje, el código no define un segundo criterio de desempate. Aquí no ordena por Orden.</p></Section><Section title="03 / Cuando no hay coincidencias"><p>Si ningún Puntaje es mayor que cero, varRespuesta queda vacía y EVA agrega: «No entendí tu pregunta 🤔 ¿puedes reformularla?».</p><p>Al terminar, actualiza varLast, apaga varEscribiendo y varStatus, y vuelve a mostrar opciones si no hay respuesta o si Title es Agradecimiento o Despedida.</p></Section><Section title="La fórmula completa del archivo"><Code control="tmr_escribiendo" property="OnTimerEnd" level={2}/></Section><Note title="Explícalo con tus palabras"><p>Una respuesta coincide con tres palabras clave y otra con una. ¿Cuál debería quedar primero? La de Puntaje 3. Este es un buscador por reglas, no un modelo de inteligencia artificial.</p></Note></>;
 if(index===4)return <><TypingDemo/><Section title="Dos temporizadores, dos tareas"><Concepts items={[["tmr_escribiendo · 1200 ms","Espera y después ejecuta la búsqueda de respuesta."],["tmr_puntitos · 400 ms","Se repite y cambia el número de puntos mientras varEscribiendo sea true."],["varStatus","Controla si thinking está visible."],["varPuntitos","Guarda el número 1, 2 o 3 para dibujar los puntos."]]}/><Flow items={['Usuario envía el mensaje','varEscribiendo = true y comienza la espera','. → .. → ...','Se procesa la respuesta al terminar','varEscribiendo = false y se oculta thinking']}/></Section><Section title="El reloj de la respuesta">{['Duration','Start'].map(p=><Code key={p} control="tmr_escribiendo" property={p}/>)}</Section><Section title="El ciclo de los puntos"><Code control="tmr_puntitos" property="OnTimerEnd"/><p><code>Mod(varPuntitos, 3) + 1</code> produce 2 después de 1, 3 después de 2 y vuelve a 1 después de 3. El botón de envío inicia varPuntitos en 1.</p>{['Duration','Repeat','Start'].map(p=><Code key={p} control="tmr_puntitos" property={p}/>)}</Section><Section title="La burbuja thinking"><Code control="thinking" property="Text"/><Code control="thinking" property="Visible"/><p>Switch elige «.», «..» o «...» según el número. Es un efecto visual de espera; los puntos no representan procesamiento de IA.</p></Section></>;
 return <><Section title="Cuatro formas de empezar"><p>Estas son las preguntas exactas que carga OnVisible.</p><div className="quick-list">{quickQuestions.map((q,i)=><div key={q}><span>0{i+1}</span>{q}</div>)}</div></Section><Section title="Conecta la galería y su botón"><Code control="galOpcionesRapidas" property="Items"/><Code control="galOpcionesRapidas" property="Visible"/><Code control="btn_choices" property="Text"/><p>ThisItem.Texto toma la pregunta de la opción seleccionada.</p></Section><Note title="La misma idea, un recorrido distinto"><p>También agrega una pregunta y una respuesta al chat, pero responde de inmediato. Consulta respuestasBot, conserva las coincidencias y elige la de menor Orden. No usa colPuntajes, no activa los temporizadores y no actualiza varLast.</p></Note><Section title="Al pulsar una opción"><Flow items={['Agregar ThisItem.Texto como mensaje del usuario','Filtrar coincidencias y ordenar por Orden ascendente','Agregar la respuesta o el mensaje de reformulación','Ocultar las opciones rápidas']}/><Code control="btn_choices" property="OnSelect" level={1}/></Section><Note title="Para cerrar la clase"><p>¿Por qué una opción rápida y la misma pregunta escrita podrían dar respuestas distintas? Compara el criterio Orden de esta fórmula con el Puntaje del temporizador.</p></Note></>;
}
function TypingDemo(){const[active,setActive]=useState(false);const[dots,setDots]=useState(1);useEffect(()=>{if(!active)return;const tick=setInterval(()=>setDots(d=>d%3+1),400);const stop=setTimeout(()=>setActive(false),1200);return()=>{clearInterval(tick);clearTimeout(stop)}},[active]);return <div className="typing-demo"><div><span className="eyebrow">DEMOSTRACIÓN VISUAL</span><h2>{active?'EVA está escribiendo'+'.'.repeat(dots):'Un pequeño momento de espera'}</h2><p>Observa el ciclo de puntos durante 1,2 segundos.</p></div><button className="primary" disabled={active} onClick={()=>{setDots(1);setActive(true)}}>{active?'Escribiendo…':'Ver animación ↗'}</button><span className="sr-only" role="status">{active?'Animación en curso':'Animación detenida'}</span></div>}
createRoot(document.getElementById('root')).render(<GuidedApp lessons={lessons} Content={Content} Badge={Badge}/>);
